image: archlinux
packages:
  - curl
  - nodejs
  - npm
  - rsync
  - jre-openjdk-headless
sources:
  - https://git.sr.ht/~bbuccianti/lambda
environment:
  deploy: deploy@69.164.203.126
secrets:
  - ffb1b60b-9c71-498c-9ba5-b8108512c1b8
tasks:
  - setup: |
      cd lambda
      curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      chmod +x lein
  - run-tests: |
      cd lambda
      npm i ws
      ./lein kaocha
  - build: |
      cd lambda
      ./lein do clean, cljsbuild once min
  - deploy: |
      cd lambda
      sshopts="-o StrictHostKeyChecking=no -p 12345"
      rsync -e "ssh $sshopts" -rP resources/ ${deploy}:lambda.buccianti.dev/
      ssh $sshopts ${deploy} '~/deploy.sh lambda.buccianti.dev'