image: archlinux
packages:
  - nodejs
  - npm
  - leiningen
  - rsync
sources:
  - https://git.sr.ht/~bbuccianti/lambda
environment:
  deploy: deploy@buccianti.dev
secrets:
  - ffb1b60b-9c71-498c-9ba5-b8108512c1b8
tasks:
  - run-tests: |
      cd lambda
      npm i ws
      lein kaocha --no-watch
  - build: |
      cd lambda
      lein do clean, cljsbuild once min
  - deploy: |
      cd lambda
      sshopts="-o StrictHostKeyChecking=no -p 12345"
      rsync -e "ssh $sshopts" -rP resources/ ${deploy}:lambda.buccianti.dev/
      ssh $sshopts ${deploy} '~/deploy.sh lambda.buccianti.dev'